# Generated by Django 4.0.5 on 2022-06-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keywords',
            new_name='tags',
        ),
    ]
